### ISSUE TITLE
Not always default branch is "main"

### ISSUE THREAD

**Issue by tekknoid** [chshersh/zbg#25]
Some project are still using "master", it can be configured anyway.

git rev-parse --abbrev-ref origin/HEAD

https://github.com/chshersh/zbg/blob/b9be80fa391a35f6ef20a4ff24af3a91c6d950fc/lib/cli.ml#LL67C61-L67C61

**Comment by chshersh** [comment]
Fixed by:

* https://github.com/chshersh/zbg/pull/24
